plugins {
    id 'com.android.application'
}

android {
    namespace '{{PACKAGE}}'
    compileSdk 34

    defaultConfig {
        applicationId "{{PACKAGE}}"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Kosong - pakai Android Framework bawaan
}
